### PR TITLE
updated to protobuffer 2.6.1

### PR DESCRIPTION
**Pull request by ffurrer**

### CODE REVIEW

**Comment by ffurrer** [comment]
@simonlynen what do I have to do to run tests, and what tests?

**Comment by simonlynen** [comment]
This one can be merged.

Once we update thirdparty submodules to point to this commit we need to run tests. Optimally you add a new ros-install file as a copy of [this](https://github.com/ethz-asl/aslam_install/blob/master/rosinstall/map_api.rosinstall) one, however pointing to the commit of thirdparty submodules which includes the new protobuf version. Then we can run a build of multi-agent mapping pointing to this new ros -install by specifying the file [here](http://129.132.38.183:8080/job/subtree_multiagent_mapping/build)

**Comment by ffurrer** [comment]
@simonlynen I don't have write access here :'(, can you merge, or give me access?

**Comment by ffurrer** [comment]
thanks

**Pull request merged**
